### ISSUE TITLE
"killed 9" error when making CAG file

### ISSUE THREAD

**Issue by LeahRoberts** [mjsull/Contiguity#20]
Hi Mitch,
I can't create a CAG file - it exits with "Killed 9". Do you know how I can fix this?
Thanks.
Leah

**Comment by mjsull** [comment]
Hi Leah,

Killed 9 means the OS killed the process, probably because it was using too
much memory. Most likely this was due to khmer, by default it uses a 8GB
block to store the hash of k-mers (so you will need 8GB free after overhead
from the OS and other programs you are running). Are you trying to run it
on a laptop with <16GB of memory.

There are a few ways around this - I am going to reduce the amount of
memory needed by default to ~4GB. You can reduce the amount of memory
needed if you run it from the command line with the '-ht_s', '-ht_n' tags -
you can read about it here
http://athyra.ged.msu.edu/~mcrusoe/build/sphinx/html/choosing-table-sizes.html

I will have an updated version of Contiguity tonight or tomorrow - I am
going to move to cx_freeze for distribution rather than pip so it will
simply be a matter of downloading it.

-Mitch

**Comment by LeahRoberts** [comment]
Ahhh thanks Mitch :) My laptop has 16GB memory, but I can't recall what else I was running at the time. I'll try again with your recommendations. 
Cheers,
Leah

**Comment by LeahRoberts** [comment]
I tried running the command again with the flags you mentioned while watching the memory usage on my laptop.

I tried two commands:

$ Contiguity -cl -co MS7884-S21_contigs_cov_trim.fasta -rf MS7884-S21_paired.fq -ht_s 2e9 -ht_n 4 -o ./

$ Contiguity -cl -co MS7884-S21_contigs_cov_trim.fasta -rf MS7884-S21_paired.fq -ht_s 4e9 -ht_n 4 -o ./

Both of these commands used in excess of 10GB memory, at one point 20+GB??

**Comment by mjsull** [comment]
Hi Leah,

What did the console output say before it crashed? Do you mind pointing me
to the files so I can give it a try?

-Mitch

**Comment by mjsull** [comment]
Hi Leah,

Haha, also you are going in the wrong direction - the memory used is ht_n *
ht_s so maybe try it with ht_n 2 and ht_s 2e9.

-Mitch

**Comment by LeahRoberts** [comment]
This is really not intuitive in Contiguity's --help. The site you pointed me to said "--n_tables/-N, and --min-tablesize/-x", so my assumption was ht_n = NUMBERS and ht_s = SIZE. The site then recommended "-N 4 -x 4e9", which translates to ht_n 4 and ht_s 4e9.
I guess you're already going to update Contiguity - but adding an extra sentence in the --help output (something like a recommended number?) would be SUPER useful so that noobs like me don't make incorrect assumptions :)

**Comment by mjsull** [comment]
Hi Leah, I think Khmer has fundamentally changed from when I implemented it and that's causing some problems. I've reduced the memory requirements and released the binaries http://mjsull.github.io/Contiguity/files.html but I'll need to take a closer look soon.
